-- ══════════════════════════════════════════════════════════════════
--  KMBNO — Generator Umów z Wykonawcami
--  Wykonaj TEN PLIK RAZ w Supabase → SQL Editor → New query → Run.
--  Ten sam projekt Supabase, co generator umów sprzedaży
--  (te same konta i hasła — nie trzeba zakładać nowych).
-- ══════════════════════════════════════════════════════════════════

-- ─── 1. Historia umów z wykonawcami ───────────────────────────────
create table if not exists public.umowy_wykonawcy (
  id         bigint generated by default as identity primary key,
  utworzono  timestamptz not null default now(),
  autor      text,
  etykieta   text,
  dane       jsonb
);

alter table public.umowy_wykonawcy enable row level security;

drop policy if exists "umowy_wyk_select" on public.umowy_wykonawcy;
create policy "umowy_wyk_select" on public.umowy_wykonawcy
  for select to authenticated using (true);

drop policy if exists "umowy_wyk_insert" on public.umowy_wykonawcy;
create policy "umowy_wyk_insert" on public.umowy_wykonawcy
  for insert to authenticated with check (true);

drop policy if exists "umowy_wyk_delete" on public.umowy_wykonawcy;
create policy "umowy_wyk_delete" on public.umowy_wykonawcy
  for delete to authenticated using (true);

create index if not exists umowy_wyk_utworzono_idx
  on public.umowy_wykonawcy (utworzono desc);


-- ─── 2. Ustawienia wspólne dla zespołu ────────────────────────────
--  Trzyma dwie rzeczy:
--   • 'konfiguracja_wykonawcy' — wybrane tablice Monday i mapowanie kolumn
--   • 'monday_token'           — token API Monday
--
--  Dzięki temu token NIE jest zapisany w kodzie na GitHubie.
--  Odczytać go może tylko osoba zalogowana w generatorze.
create table if not exists public.ustawienia (
  klucz          text primary key,
  wartosc        jsonb,
  zaktualizowano timestamptz not null default now()
);

alter table public.ustawienia enable row level security;

drop policy if exists "ustawienia_select" on public.ustawienia;
create policy "ustawienia_select" on public.ustawienia
  for select to authenticated using (true);

drop policy if exists "ustawienia_insert" on public.ustawienia;
create policy "ustawienia_insert" on public.ustawienia
  for insert to authenticated with check (true);

drop policy if exists "ustawienia_update" on public.ustawienia;
create policy "ustawienia_update" on public.ustawienia
  for update to authenticated using (true) with check (true);


-- ─── 3. Sprawdzenie ───────────────────────────────────────────────
-- Po uruchomieniu powinny pojawić się dwa wiersze:
select table_name, 'OK' as status
from information_schema.tables
where table_schema = 'public'
  and table_name in ('umowy_wykonawcy', 'ustawienia');
